### PR TITLE
Fixes Multiple Issues / Refactors Code / Adds Additional Op-Code Support

### PR DESCRIPTION
**Pull request by BrianGodsend**
Fixes issues on DS conversion for LIKE, EXTNAME, EXTFMT, and use of special reserved words (*PROC, *STATUS, etc.). Specific issues fixed:
* Fixes BrianGarland/vscode-rpgfree#48
* Fixes BrianGarland/vscode-rpgfree#52
* Fixes BrianGarland/vscode-rpgfree#62
* Fixes BrianGarland/vscode-rpgfree#77
* Fixes BrianGarland/vscode-rpgfree#78

Additional D-Spec clean up.  Specific issues fixed:
* Fixes BrianGarland/vscode-rpgfree#32
* Fixes BrianGarland/vscode-rpgfree#35
* Fixes BrianGarland/vscode-rpgfree#45
* Fixes BrianGarland/vscode-rpgfree#50
* Fixes BrianGarland/vscode-rpgfree#61
* Fixes BrianGarland/vscode-rpgfree#81
* Fixes BrianGarland/vscode-rpgfree#82

Corrected indentation of procedure interface, parameters, and data definitions inside a procedure.  This fixes the issue:
* Fixes BrianGarland/vscode-rpgfree#83

Additional issues addressed in this pull request include:
* Resolves BrianGarland/vscode-rpgfree#16
* Fixes BrianGarland/vscode-rpgfree#53
* Fixes BrianGarland/vscode-rpgfree#70
* Fixes BrianGarland/vscode-rpgfree#85
* Fixes BrianGarland/vscode-rpgfree#86
* Fixes BrianGarland/vscode-rpgfree#88
* Fixes BrianGarland/vscode-rpgfree#89
* Fixes BrianGarland/vscode-rpgfree#90
* Fixes BrianGarland/vscode-rpgfree#91

Additional patches incorporated from changes made by @DavidShears:
* Fixes BrianGarland/vscode-rpgfree#56

### CODE REVIEW

**Comment by BrianGarland** [comment]
@BrianGodsend Because of the massive pull request I just merged I need your changes to be made based on that version to merge them.    Can you pull the new code and make your changes there?

**Comment by worksofliam** [comment]
@BrianGodsend There is also a test suite now, so it'd be cool to ensure that after `main` has been merged into this branch that the tests still pass (`rpm run test`) and then you can also add your own tests!

**Comment by GlennGundermann** [comment]
Hi there,
I'm new to VS Code.  I see this Pull will fix some issues I'm having.  How long will it take for this to get promoted so us end-users can get the fix?
Thank you.

**Comment by BrianGarland** [comment]
@GlennGundermann The complication with this pull request is that it is based on code from before some major changes and needs to be merged with those changes before I can accept it.   I have asked @BrianGodsend to do this but have not heard back yet.

**Comment by BrianGarland** [comment]
It's been over 6 months with no response.  I'm closing this pull request as it looks like the author is no longer active.

**Pull request closed without merging**
